### ISSUE TITLE
Loss overflow issue

### ISSUE THREAD

**Issue by Carlisle-Liu** [nnizhang/CADC#2]
Hi,

I've encountered a loss overflow issue as shown in the attached screenshot when attempting to train the model following the instructions. May I know how can i fix this problem?

Thank you very much for your help
![Screenshot from 2021-12-14 22-56-36](https://user-images.githubusercontent.com/49419716/145994067-49deb67d-4ac0-434e-b4a7-62f43adcd9e9.png)

Kind regards,
Jiawei

**Comment by nnizhang** [comment]
I did not get this error. Do you follow the default training setting? Or please check whether the training data is correct.

**Comment by Carlisle-Liu** [comment]
Hi,

Thank you for your reply.

I did follow the default training setting and downloaded the training data as instructed. But could you let me know the folder structure in the Data folder. Currently I have placed them as shown in the 1st screenshot. But according to the codes in the dataset.py as shown in the 2nd screenshot, should COCO, Syn, ReverseSyn be in a single folder, sorted by their groups?

Thank you.


Kind regards,
Jiawei

![Screenshot from 2021-12-15 15-54-33](https://user-images.githubusercontent.com/49419716/146125760-bcc6507c-60f5-4336-a8b9-8a0a02b70fb5.png)

![Screenshot from 2021-12-14 22-56-36](https://user-images.githubusercontent.com/49419716/146125770-8f3bd92c-af5c-43bb-ae59-1636034e4b4e.png)

**Comment by hehaiyang111** [comment]
Hi,

When I ran the training script, I encountered RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same. Did you encounter the same problem during training?

**Comment by Carlisle-Liu** [comment]
That might be associated with the environment, e.g. package versions. But still I encounter the gradient explosion after just few iterations, rendering the published model untrainable.

**Comment by Carlisle-Liu** [comment]
The gradient explosion issue was caused by installing the apex package in the environment.
